configuration/urls.py
from django.conf.urls import url
from .views import ATTACK_CHOICES
from django.urls import path

from . import views

app_name = "configuration"

urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('logger-frame', views.logger_frame, name='logger-frame'),
    path('get-log', views.get_log, name='get-log'),
    path('clean-log', views.clean_log, name='clean-log'),
    path('configuration-complete', views.config_complete,
         name='config-complete'),
    path('no-attack', views.no_attack, name='no-attack'),
    path('user-code-leak', views.ucl, name='ucl'),
    path('device-code-leak', views.dcl, name='dcl'),
    path('man-in-the-middle', views.mitm, name='mitm'),
    path('remote-phishing', views.rp, name='rp'),
    path('csrf-with-qr-code', views.csrfqr, name='csrfqr'),
    path('corrupted-device-client', views.cdc, name='cdc'),
    path('denial-of-service', views.dos, name='dos'),
]

device/urls.py
from django.urls import path
from . import views

app_name = "device"

urlpatterns = [
    path('', views.index, name='index'),
    path('grant', views.grant, name='grant'),
    path('grant-successful', views.grant_successful, name='grant-successful'),
]

device_grant_sec_simulation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from device_grant_sec_simulation import views as views

urlpatterns = [
    path('', views.startpage),
    path('admin/', admin.site.urls),
    path('attacker/', include('attacker.urls'), name='attacker'),
    path('configuration/', include('configuration.urls'), name='configuration'),
    path('device/', include('device.urls'), name='device'),
    path('authorization-server/', include('authorization_server.urls'),
         name='authorization_server'),
]

configuration/views.py
import os
from django.db.utils import OperationalError
from django.http.response import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_sameorigin
import requests
from .models import config_object, reset_config_db
from .models import ATTACK_CHOICES, RP_CHOICES, UCL_CHOICES, DCL_CHOICES, MITM_CHOICES, CDC_CHOICES
from device.models import reset_device_db
from configuration.models import reset_config_db
from authorization_server.models import reset_AS_db
from attacker.models import reset_attacker_db
import logging

logger = logging.getLogger(__name__)


def reset_db():
    """Reset attacker, AS, and device databases"""
    reset_attacker_db()
    reset_AS_db()
    reset_device_db()

def index(request):
    """Configuration and logging frames, resets databases"""
    context = {'attack_choices': ATTACK_CHOICES,
               'description': 'Configuration of Attack Scenario'}
    return render(request, 'configuration/index.html', context)


@xframe_options_sameorigin
def config(request):
    reset_db()
    reset_config_db()
    """Attack scenario options"""
    context = {'attack_choices': ATTACK_CHOICES,
               'description': 'Configuration of Attack Scenario'}
    return render(request, 'configuration/config.html', context)


@xframe_options_sameorigin
def logger_frame(request):
    """Returns logger html-page"""
    return render(request, 'configuration/logger.html')


@xframe_options_sameorigin
def get_log(request):
    """Returns current content of logger in HTML format"""
    lines = open(os.getcwd() + "/logger.log", "r").read().split('\n')
    log = ""
    ignore = 0
    for line in lines:
        # Ignore celery debug waarning
        if "_showwarnmsg" in line:
            ignore = 5
        if ignore > 0:
            ignore -= 1
        else:
            log += line + "<br>"
    return HttpResponse(log)


@xframe_options_sameorigin
def clean_log(request):
    """Reset logging file"""
    open(os.getcwd() + "/logger.log", "w")
    return HttpResponse()


@xframe_options_sameorigin
def config_complete(request):
    """Config complete, displays configuration and initiatesattacks in \
        various scenarios"""
    if request.method == 'GET':
        config = config_object() 
        link = reverse('device:index')

        reset_db()

        if config.attack_choice == 'ucl' and config.ucl_choice == "bf":
            requests.post(request.build_absolute_uri(
                reverse('attacker:brute-force-user-code')))
        elif config.attack_choice == 'dcl' and config.dcl_choice == "bf":
            requests.post(request.build_absolute_uri(
                reverse('attacker:brute-force-device-code')))
        elif config.attack_choice == 'rp':
            link = reverse('attacker:rp')
        elif config.attack_choice == 'csrfqr':
            link = reverse('attacker:csrfqr')
        elif config.attack_choice == 'dos':
            requests.post(request.build_absolute_uri(reverse('attacker:dos')))

        if (config.attack_choice == 'ucl' and config.ucl_choice == 'sep') \
                or (config.attack_choice == "dcl" and config.dcl_choice == 'sep'):
            sep = "Note that this attack only works when using verification_uri_complete!"
        else: 
            sep = ""
        context = {'config': str(config), 'link': link, 'sep': sep}
        return render(request, 'configuration/configuration-complete.html',
                      context)

    else:
        return HttpResponseForbidden()


@xframe_options_sameorigin
def no_attack(request):
    """Default scenario with no attack"""
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "no-attack"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        return render(request, 'configuration/no-attack.html')

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        config.attack_choice = "no-attack"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        logger.warning(config)
        return HttpResponseRedirect(reverse('configuration:config-complete'))


@xframe_options_sameorigin
def ucl(request):
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "ucl"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        context = {'ucl_choices': UCL_CHOICES}
        return render(request, 'configuration/user-code-leak.html', context)

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        config.attack_choice = "ucl"
        config.ucl_choice = request.POST['choice']
        config.user_code_entropy = request.POST['entropy']
        if 'rate_limiting' in request.POST:
            config.rate_limiting_ucl = True
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        logger.warning(config)
        return HttpResponseRedirect(reverse('configuration:config-complete'))


@xframe_options_sameorigin
def dcl(request):
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "dcl"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        context = {'dcl_choices': DCL_CHOICES}
        return render(request, 'configuration/device-code-leak.html', context)

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        config.attack_choice = "dcl"
        config.dcl_choice = request.POST['choice']
        if request.POST['choice'] == "bf":
            config.device_code_entropy = request.POST['entropy']
        if 'rate_limiting' in request.POST:
            config.rate_limiting_dcl = True
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        logger.warning(config)
        return HttpResponseRedirect(reverse('configuration:config-complete'))


@xframe_options_sameorigin
def mitm(request):
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "mitm"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        context = {'mitm_choices': MITM_CHOICES}
        return render(request, 'configuration/man-in-the-middle.html', context)

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        with_token_respone = request.POST.get('with_token_response', False)
        if with_token_respone:
            config.mitm_choice = 'with_token_response'
        config.attack_choice = "mitm"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        logger.warning(config)
        return HttpResponseRedirect(reverse('configuration:config-complete'))


@xframe_options_sameorigin
def rp(request):
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "rp"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        context = {'rp_choices': RP_CHOICES}
        return render(request, 'configuration/remote-phishing.html', context)

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        config.attack_choice = "rp"
        config.rp_choice = request.POST['choice']
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        logger.warning(config)
        return HttpResponseRedirect(reverse('configuration:config-complete'))


@xframe_options_sameorigin
def csrfqr(request):
    if request.method == 'GET':
        reset_config_db()
        config = config_object()
        config.attack_choice = "csrfqr"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass
        return render(request, 'configuration/csrf-with-qr-code.html')

    else:
        # save config and redirect to config-complete
        config = config_object()
        if 'show_device_name' in request.POST:
            config.show_device_name = True
        if 'show_scope' in request.POST:
            config.show_scope = True
        config.attack_choice = "csrfqr"
        while True:
            try:
                config.save(); break
            except OperationalError:
                pass

configuration/templates/configuration/base_config.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Configuration</title>
    <link rel="stylesheet" href="{% static 'configuration/styles.css' %}">
</head>
<body>
<div id="content">
    <div id="title"><h1>Configuration of Attack Scenario<h1></div>
    <div id="description"><h2>{% block description %}{% endblock %}</h2></div>
    <div id="config">{% block config %}{% endblock %}</div>
</div>
</body>
</html>

configuration/templates/configuration/config.html
{% extends "configuration/base_config.html" %}

{% block config %}
<h2>Please choose an attack scenario:</h2>
<ol>
{% for key, value in attack_choices.items %}
    <li><a href="{% url 'configuration:'|add:key %}">{{ value }}</a></li>
{% endfor %}
</ol>
{% endblock %}

configuration/templates/configuration/configuration-complete.html
{% extends "configuration/base_config.html" %}

{% block description %} Configuration Complete! {% endblock %}

{% block config %}
<p>{{config}}</p>
{% if sep != "" %}
<p><b>{{sep}}</b></p>
{% endif %}
<br>
<div style="text-align: center;">
<button  onclick="window.open('{{link}}', '_blank')">Start</button>
</div>

<hr style="border-top: 2px solid #bbb; margin: 3em 0">
<div style="text-align: center;">
    <button onclick="window.open('{% url 'configuration:config' %}', '_self')">Try out another scenario</button>
</div>

{% endblock %}

configuration/templates/configuration/corrupted-device-client.html
{% extends "configuration/base_config.html" %}
{% block description %}Corrupted Device Client{% endblock %}

{% block config %}
<form action="{% url 'configuration:cdc' %}" method="post">
    {% csrf_token %}
    {% for key, value in cdc_choices.items %}
    {% if key != '' %}
    <input type="checkbox" name="{{ key }}" id="cdc{{ forloop.counter }}">
    <label for="cdc{{ forloop.counter }}">{{ value }}</label><br>
    {% endif %}
    {% endfor %}
    <br></br>
    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/csrf-with-qr-code.html
{% extends "configuration/base_config.html" %}
{% block description %}Cross-Site-Request-Forging with QR-Code{% endblock %}

{% block config %}
<form action="{% url 'configuration:csrfqr' %}" method="post">
    {% csrf_token %}
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label><br>
    <input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br>
    <br>
    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/denial-of-service.html
{% extends "configuration/base_config.html" %}
{% block description %}Denial of Service{% endblock %}

{% block config %}
<form action="{% url 'configuration:dos' %}" method="post">
    {% csrf_token %}
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label><br>
    <input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br>
    <br>
    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/device-code-leak.html
{% extends "configuration/base_config.html" %}
{% block description %}Device Code Leak{% endblock %}

{% block config %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'configuration:dcl' %}" method="post">
    {% csrf_token %}
    {% for key, value in dcl_choices.items %}
    {% if key != '' %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ key }}" {% if key == "bf" %}
        onchange="document.getElementById('bf_param').style.display = 'block';" {% else %}
        onchange="document.getElementById('bf_param').style.display = 'none';" {% endif %} {% if forloop.counter == 1 %}
        checked {% endif %}>
    <label for="choice{{ forloop.counter }}">{{ value }}</label><br>
    {% endif %}
    {% endfor %}
    <div id="bf_param" style="display: none;">
        <hr style="border-top: 2px solid #bbb; margin: 1em 0em">
        <label for="entropy">Entropy of device code: </label>
        <input type="range" id="entropy" list="tickmarks"
            oninput="document.getElementById('value').innerHTML = this.value;" style="width:40em;" name="entropy"
            step="1" min="2" max="20">
        <em id="value" style="font-style: normal;">11</em>
        <em style="font-style: normal;"> Bits</em>
        <datalist id="tickmarks">
            <option value="2" label="2"></option>
            <option value="4"></option>
            <option value="6"></option>
            <option value="8" label="8"></option>
            <option value="10"></option>
            <option value="12"></option>
            <option value="14" label="14"></option>
            <option value="16"></option>
            <option value="18"></option>
            <option value="20" label="20"></option>
        </datalist>
        <p>Note: Depending on the device the server is run on, the attack may be feasible up to a user_code entropy of about 12.</p>
        <input type="checkbox" name="rate_limiting" id="rate_limiting">
        <label for="rate_limiting">Rate-limiting: Authorization server limits rate for polling per polling party (here just for the attacker, max 3 attempts/s)</label>
    </div>
    <hr style="border-top: 2px solid #bbb; margin: 1em 0">
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label>
    <br>
    <input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br><br>
    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Configuration and Logger</title>
    <link rel="stylesheet" href="{% static 'configuration/styles.css' %}">
</head>
<body style="background-color: #eee;">
<div class="box">
  <iframe class="frame" src="{% url 'configuration:config' %}" width="100%" style="height: 95vh; overflow: scroll;" frameborder="0" scrolling="no" align="left"> </iframe>
</div>

<div class="box">
  <iframe class="frame" src="{% url 'configuration:logger-frame' %}" width="100%" style="height: 95vh;" frameborder="0" align="right"></iframe>
</div>
</body>
</html>

configuration/templates/configuration/logger.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logger</title>
    <link rel="stylesheet" href="{% static 'configuration/styles.css' %}">
</head>
<script>
// request current content of logger.log and update on page
function updateLog() {
    ajaxGet(function(data) {
        document.getElementById('log').innerHTML = data;
    });
}

// ajax GET request for updateLog
function ajaxGet(callback) {
    var request = new XMLHttpRequest();
    request.onreadystatechange = function() {
        if (request.readyState == 4 && request.status == 200) {
            try {
                var data = request.responseText;
            } catch(error) {
                console.log(error.message + " in " + request.responseText)
                return;
            }
            callback(data);
        }
    }
    request.open("GET", "{% url 'configuration:get-log' %}", true);
    request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
    request.send();
}

// clean logger request
function emptyLog(callback) {
    var request = new XMLHttpRequest();
    request.open("GET", "{% url 'configuration:clean-log' %}", true);
    request.send();
}

// start logging
setInterval(updateLog, 3000);

</script>
<body>
<div style="position:fixed; top: 0; width: 100%; background: white; z-index: 1; margin: 0 auto;">
    <div><h1> Logger </h1></div>
    <div style="position:fixed; top: 2.3em; right: 1.5em"><button onclick="emptyLog();">Reset</button></div>
</div>
<div style="padding-top: 5em;"><p id="log"></p></div>
</body>
</html>

configuration/templates/configuration/man-in-the-middle.html
{% extends "configuration/base_config.html" %}
{% block description %}Man in the Middle{% endblock %}

{% block config %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'configuration:mitm' %}" method="post">
    {% csrf_token %}
    {% for key, value in mitm_choices.items %}
    {% if key != '' %}
    <input type="checkbox" name="{{ key }}" id="mitm{{ forloop.counter }}">
    <label for="mitm{{ forloop.counter }}">{{ value }}</label><br>
    {% endif %}
    {% endfor %}
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label>
    <br><input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br></br>
    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/no-attack.html
{% extends "configuration/base_config.html" %}
{% block description %}No Attack{% endblock %}

{% block config %}
<form action="{% url 'configuration:no-attack' %}" method="post">
    {% csrf_token %}
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label>
    <br><input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br></br>

    <button type="submit">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/remote-phishing.html
{% extends "configuration/base_config.html" %}
{% block description %}Remote Phishing{% endblock %}

{% block config %}
<form method="post" autocomplete="off" action="{% url 'configuration:rp' %}">
    {% csrf_token %}
    <input autocomplete="false" name="hidden" type="text" style="display:none;">
    {% for key, value in rp_choices.items %}
    {% if key != '' %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ key }}"
    {% if forloop.counter == 1 %}
        checked {% endif %}>
    <label for="choice{{ forloop.counter }}">{{ value }}</label><br>
    {% endif %}
    {% endfor %}
    <hr style="border-top: 2px solid #bbb; margin: 1em 0">
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label>
    <br><input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br><br>
    <button type="submit" name="sign-in">Continue</button>
</form>
{% endblock %}

configuration/templates/configuration/user-code-leak.html
{% extends "configuration/base_config.html" %}
{% block description %}User Code Leak{% endblock %}

{% block config %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'configuration:ucl' %}" method="post">
    <h3>Sub-Scenario</h3>
    {% csrf_token %}
    {% for key, value in ucl_choices.items %}
    {% if key != '' %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ key }}" {% if key == "bf" %}
        onchange="document.getElementById('bf_param').style.display = 'block';" {% else %}
        onchange="document.getElementById('bf_param').style.display = 'none';" {% endif %} {% if forloop.counter == 1 %}
        checked {% endif %}>
    <label for="choice{{ forloop.counter }}">{{ value }}</label><br>
    {% endif %}
    {% endfor %}

    <div id="bf_param" style="display: none;">
        <hr style="border-top: 2px solid #bbb; margin: 1em 0em">
        <label for="entropy">Entropy of user code: </label>
        <input type="range" id="entropy" list="tickmarks"
            oninput="document.getElementById('value').innerHTML = this.value;" style="width:40em;" name="entropy"
            step="1" min="2" max="20">
        <em id="value" style="font-style: normal;">11</em>
        <em style="font-style: normal;"> Bits</em>
        <datalist id="tickmarks">
            <option value="2" label="2"></option>
            <option value="4"></option>
            <option value="6"></option>
            <option value="8" label="8"></option>
            <option value="10"></option>
            <option value="12"></option>
            <option value="14" label="14"></option>
            <option value="16"></option>
            <option value="18"></option>
            <option value="20" label="20"></option>
        </datalist>
        <p>Note: Depending on the device the server is run on, the attack is usually successful up to a user_code entropy of about 12.</p>
        <input type="checkbox" name="rate_limiting" id="rate_limiting">
        <label for="rate_limiting">Rate-limiting: Authorization server limits rate for login attempts per user (max 3 attempts/s)</label>
    </div>
    <hr style="border-top: 2px solid #bbb; margin: 1em 0">
    <input type="checkbox" name="show_device_name" id="show_device_name">
    <label for="show_device_name">AS shows what device is registered</label>
    <br><input type="checkbox" name="show_scope" id="show_scope">
    <label for="show_scope">AS shows requested scope</label><br><br>
    <button type="submit">Continue</button>
</form>
{% endblock %}