configuration/urls.py
from django.conf.urls import url
from .views import ATTACK_CHOICES
from django.urls import path

from . import views

app_name = "configuration"

urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('logger-frame', views.logger_frame, name='logger-frame'),
    path('get-log', views.get_log, name='get-log'),
    path('clean-log', views.clean_log, name='clean-log'),
    path('configuration-complete', views.config_complete,
         name='config-complete'),
    path('no-attack', views.no_attack, name='no-attack'),
    path('user-code-leak', views.ucl, name='ucl'),
    path('device-code-leak', views.dcl, name='dcl'),
    path('man-in-the-middle', views.mitm, name='mitm'),
    path('remote-phishing', views.rp, name='rp'),
    path('csrf-with-qr-code', views.csrfqr, name='csrfqr'),
    path('corrupted-device-client', views.cdc, name='cdc'),
    path('denial-of-service', views.dos, name='dos'),
]

device/urls.py
from django.urls import path
from . import views

app_name = "device"

urlpatterns = [
    path('', views.index, name='index'),
    path('grant', views.grant, name='grant'),
    path('grant-successful', views.grant_successful, name='grant-successful'),
]

device_grant_sec_simulation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from device_grant_sec_simulation import views as views

urlpatterns = [
    path('', views.startpage),
    path('admin/', admin.site.urls),
    path('attacker/', include('attacker.urls'), name='attacker'),
    path('configuration/', include('configuration.urls'), name='configuration'),
    path('device/', include('device.urls'), name='device'),
    path('authorization-server/', include('authorization_server.urls'),
         name='authorization_server'),
]

templates/startpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Device Grant SEC Simulation</title>
    <link rel="stylesheet" href="{% static 'configuration/styles.css' %}">
</head>
<body style="background-color: #eee; margin: 1.5em">
<div style="text-align: center; padding: 3em 2em 6em 2em; margin: 0em auto; background-color: white; border-radius: 10px; box-shadow: 0px 0px 4px 2px #bbb;">
    <h1>Device Grant SEC Simulation</h1>
    <div style="max-width: 500px; margin: 0em auto;">
        <p> Welcome to a simulation of possible attack scenarios against the OAuth Device Authorization Grant ("Device Flow").</p>
        <p>
            This project is part of a research project with the goal to examine the practical security of the Device Flow. The Grant enables a user to connect devices that lack an appropriate interface for password input or other authentication procedures (e.g. Hardware Token) to his account at an online service.
        </p>
        <p>
            The simulation includes an authentication server (AS), a client device (in form of a simple web application), and an attacker. The attack can be configured for various attack vectors.
        </p>
    </div>
    <br>
    <button onclick="window.open('{% url 'configuration:index' %}', '_self')">Continue</button>
</div>

</body>
</html>